using UnityEngine;

namespace Assets.Scripts
{
    public class SpawnManager : MonoBehaviour
    {
        // public variables
        [Tooltip("Enemy Prefab")]
        public GameObject enemyPrefab;

        [HideInInspector] public int waveNumber = 1;

        // private variables
        private const float spawnRange = 9.0f;

        // Start is called before the first frame update
        private void Start()
        {
            SpawnEnemyWave(waveNumber);
        }

        // Spawns a number of enemies at random positions of the island
        private void SpawnEnemyWave(int enemiesToSpawn)
        {
            for (var i = 0; i < enemiesToSpawn; i++)
            {
                // creates a new instance of enemyPrefab at the position generated by GenerateSpawnPos()
                // and with the rotation of enemyPrefab
                Instantiate(enemyPrefab, GenerateSpawnPos(), enemyPrefab.transform.rotation);
            }
        }

        private static Vector3 GenerateSpawnPos()
        {
            // This function generates a random spawn position for an enemy in the game world.
            // The spawn position is a Vector3 with a random x and z value between -spawnRange and spawnRange
            // and a y value of 0.
            var spawnPosX = Random.Range(spawnRange, -spawnRange);
            var spawnPosZ = Random.Range(spawnRange, -spawnRange);
            Vector3 spawnPos = new(spawnPosX, 0, spawnPosZ);
            return spawnPos;
        }

        [HideInInspector]
        public int activeEnemies;

        // Update is called once per frame
        private void Update()
        {
            // Finds all the Game Objects of type Enemy in the scene and stores them in an array and
            // assigns Active Enemy number in the scene to the variable ActiveEnemies.
            // Then checks if the number of active enemies is 0 and if so,
            // spawns a new wave of enemies with one enemy more than the previous wave.
            activeEnemies = FindObjectsOfType<Enemy>().Length;
            if (activeEnemies != 0) return;
            waveNumber++;
            SpawnEnemyWave(waveNumber);
        }
    }
}