using UnityEngine;

namespace Assets.Scripts
{
    public class SpawnManager : MonoBehaviour
    {
        // public variables
        [Tooltip("Enemy Prefab")]
        public GameObject enemyPrefab;

        // private variables
        private readonly float spawnRange = 9.0f;

        // Start is called before the first frame update
        void Start()
        {
            // creates a new instance of enemyPrefab at the postion generated by GenerateSpawnPos()
            // and with the rotation of enemyPrefab
            Instantiate(enemyPrefab, GenerateSpawnPos(), enemyPrefab.transform.rotation);
        }

        Vector3 GenerateSpawnPos()
        {
            // This function generates a random spawn position for an enemy in the game world.
            // The spawn position is a Vector3 with a random x and z value between -spawnRange and spawnRange
            // and a y value of 0.
            float spawnPosX = Random.Range(spawnRange, -spawnRange);
            float spawnPosZ = Random.Range(spawnRange, -spawnRange);
            Vector3 spawnPos =  new(spawnPosX, 0, spawnPosZ);
            return spawnPos;
        }

        // Update is called once per frame
        void Update()
        {
        
        }
    }
}
